/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/Account.vue')['default']
    AppPanel: typeof import('./src/components/base/AppPanel.vue')['default']
    AppShell: typeof import('./src/components/layout/AppShell.vue')['default']
    BTPublish: typeof import('./src/components/BTPublish.vue')['default']
    Check: typeof import('./src/components/Check.vue')['default']
    CreateTask: typeof import('./src/components/CreateTask.vue')['default']
    Edit: typeof import('./src/components/Edit.vue')['default']
    ElAlert: typeof import('element-plus/es')['ElAlert']
    ElButton: typeof import('element-plus/es')['ElButton']
    ElButtonGroup: typeof import('element-plus/es')['ElButtonGroup']
    ElCheckbox: typeof import('element-plus/es')['ElCheckbox']
    ElCol: typeof import('element-plus/es')['ElCol']
    ElCollapse: typeof import('element-plus/es')['ElCollapse']
    ElCollapseItem: typeof import('element-plus/es')['ElCollapseItem']
    ElDialog: typeof import('element-plus/es')['ElDialog']
    ElEmpty: typeof import('element-plus/es')['ElEmpty']
    ElForm: typeof import('element-plus/es')['ElForm']
    ElFormItem: typeof import('element-plus/es')['ElFormItem']
    ElIcon: typeof import('element-plus/es')['ElIcon']
    ElInput: typeof import('element-plus/es')['ElInput']
    ElInputNumber: typeof import('element-plus/es')['ElInputNumber']
    ElLink: typeof import('element-plus/es')['ElLink']
    ElOption: typeof import('element-plus/es')['ElOption']
    ElPopover: typeof import('element-plus/es')['ElPopover']
    ElProgress: typeof import('element-plus/es')['ElProgress']
    ElRadio: typeof import('element-plus/es')['ElRadio']
    ElRadioButton: typeof import('element-plus/es')['ElRadioButton']
    ElRadioGroup: typeof import('element-plus/es')['ElRadioGroup']
    ElRow: typeof import('element-plus/es')['ElRow']
    ElScrollbar: typeof import('element-plus/es')['ElScrollbar']
    ElSelect: typeof import('element-plus/es')['ElSelect']
    ElSelectV2: typeof import('element-plus/es')['ElSelectV2']
    ElSwitch: typeof import('element-plus/es')['ElSwitch']
    ElTable: typeof import('element-plus/es')['ElTable']
    ElTableColumn: typeof import('element-plus/es')['ElTableColumn']
    ElTag: typeof import('element-plus/es')['ElTag']
    ElTooltip: typeof import('element-plus/es')['ElTooltip']
    EpisodeCreateForm: typeof import('./src/components/EpisodeCreateForm.vue')['default']
    EpisodeEdit: typeof import('./src/components/EpisodeEdit.vue')['default']
    FeatureCreateForm: typeof import('./src/components/FeatureCreateForm.vue')['default']
    Finish: typeof import('./src/components/Finish.vue')['default']
    ForumPublish: typeof import('./src/components/ForumPublish.vue')['default']
    Modify: typeof import('./src/components/Modify.vue')['default']
    ProjectModeSelectDialog: typeof import('./src/components/ProjectModeSelectDialog.vue')['default']
    PtSiteAccounts: typeof import('./src/components/PtSiteAccounts.vue')['default']
    Quickstart: typeof import('./src/components/Quickstart.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SidebarNav: typeof import('./src/components/layout/SidebarNav.vue')['default']
    StageWorkspace: typeof import('./src/components/base/StageWorkspace.vue')['default']
    StatusChip: typeof import('./src/components/feedback/StatusChip.vue')['default']
    TaskList: typeof import('./src/components/TaskList.vue')['default']
    TopBar: typeof import('./src/components/layout/TopBar.vue')['default']
  }
  export interface ComponentCustomProperties {
    vLoading: typeof import('element-plus/es')['ElLoadingDirective']
  }
}
